markdown: rdiscount
highlighter: pygments
permalink: /posts/:title
rdiscount:
  extensions: [smart]
title : Bharadwaj
production_url : http://bharath12345.github.io
url: http://bharath12345.github.io
description: "thoughts, musings, writings"
disqus_shortname: bharathtalks
analytics: 
  provider : google
  google : 
      tracking_id : 'UA-42349821-1'
gauges: 
author :
  name : Bharadwaj
  github : bharath12345
  twitter : bharathtalks
  email: bharath12345@gmail.com
