markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]
title : Bharadwaj
production_url : http://bharath12345.github.io
description: "thoughts, musings, writings"
disqus_shortname: bharathtalks
analytics: 
gauges: 
author :
  name : Bharadwaj
  github : bharath12345
  twitter : bharathtalks
  email: bharath12345@gmail.com
